---
version: "3.8"
services:
  box-build:
    build:
      context: .
      dockerfile: Dockerfile_build
    volumes:
      - art:/opt

  box-run:
    build:
      context: .
      dockerfile: Dockerfile_run
    volumes:
      - art:/opt
    ports:
      - "8080:8080"
    depends_on:
      - box-build
volumes:
  art: